twig:
    file_name_pattern: '*.twig'
    globals:
        menuItems: '@App\Service\AdminService'
        sidebarTitles: '@App\Repository\SidebarTitlesRepository'



when@test:
    twig:
        strict_variables: true
